### ISSUE TITLE
Remember size and position

### ISSUE THREAD

**Issue by DrXenos** [LesFerch/OldExplorer#3]
It would be nice is OldExplorer remembered its size and position on the screen. As a workaround, I found that I can adjust the Control Panel to the size I want and the next time I open OldExplorer, it will use that size/pos.

**Comment by LesFerch** [comment]
It's not an issue with the OldExplorer. It's actually standard behavior. The Control Panel window size and position is only remembered if you close the window while it's in Control Panel view. Once you press up arrow to get to the Explorer view, it ceases to remember the position.

Presumably, you're using OldExplorer because you want to use the old Details pane. Otherwise, the solution would be to use [SwitchExplorer](https://lesferch.github.io/SwitchExplorer/). The best compromise I can suggest is to use SwitchExplorer in combination with OldNewExplorer to get the Windows 7 style Details pane.
